### PR TITLE
Internationalisation support for calendars

### PR DESCRIPTION
**Pull request by skymen**
Hi, I added the props to allow for interationnalization.

### CODE REVIEW

**Comment by praveenpuglia** [comment]
Hi!

Thanks so much for the code. Great first PR. 👍 

Can you please also do the following to make sure this is the best ever PR here?
- add the updated props in the readme with description or link to the ones that map to vuetify's datepicker.
- update the `labels` prop's description to add the `preset` key?

Thanks so much. This was really quick! :)

**Comment by praveenpuglia** [comment]
Also, if you would like to want to contribute more to this, I can give you collaborator access and we can make this component much better :)

**Comment by skymen** [comment]
Yeah I'll do this now,
I don't think I'll need to add more stuff to this for now. However, if at some point I feel that I'll need to make more stuff with this I will definitely contribute more :)

**Comment by skymen** [comment]
Ok done 👌

**Comment by praveenpuglia** [comment]
It's perfect. Merging this. :)

**Pull request merged**
