### PR TITLE
Style selected date-range

### PR DESCRIPTION
**Pull request by mariokresic**
--add all dates from dateRange to event prop and then style event div to highlight selected dates

### CODE REVIEW

**Comment by praveenpuglia** [comment]
Saw it now. Will test this out and release if all looks good :)

**Comment by mariokresic** [comment]
Hello, I found some more time to edit the code. Can you please take a look now? I'll also explain css (z-index) if needed.

**Comment by praveenpuglia** [comment]
Also, can you please add screenshot from your changes so I can check if I am seeing the right thing?

**Comment by mariokresic** [comment]
Hi,
maybe you have your css cashed in your browser? This is from demo `npm run dev`

(sry for ugly color, I should change it :) )
screenshot from 2018-09-13 11-07-52
screenshot from 2018-09-13 11-08-36

**Comment by praveenpuglia** [comment]
Hi @mariokresic are you also facing the issue with css styles not getting applies while running `yarn dev` ? 

Need help debugging this.

**Comment by mariokresic** [comment]
Hi, sorry for very late answer! I'm kinda short on time to be "active" here, but please feel free to ask me anytime if you need help with something, you can even better send me an email. I will be glad to help if I'm able to at the time.

**Pull request merged**
